# Generated by Django 4.2.23 on 2025-07-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, help_text="User's address", null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact phone number",
                max_length=20,
                null=True,
            ),
        ),
    ]
