# Generated by Django 4.2.23 on 2025-07-29 07:48

import Services.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Services.users.models.CustomUserManager()),
            ],
        ),
    ]
